"""Initial schema with users days expenses and composite indexes

Revision ID: b0c5b69d95d5
Revises: 
Create Date: 2026-07-30 15:25:13.501766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c5b69d95d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_days_user_day', 'days', ['user_id', 'day'], unique=False)
    op.create_index(op.f('ix_days_day'), 'days', ['day'], unique=False)
    op.create_index('idx_expenses_day_created', 'expenses', ['day_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expenses_day_created', table_name='expenses')
    op.drop_index(op.f('ix_days_day'), table_name='days')
    op.drop_index('idx_days_user_day', table_name='days')
    # ### end Alembic commands ###
